name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install/Update AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Deploy to S3
      run: |
        if aws s3 ls "s3://$S3_BUCKET" 2>&1 | grep -q 'NoSuchBucket'; then
          echo "Bucket does not exist. Creating bucket: $S3_BUCKET"
          if [ "$AWS_REGION" = "us-east-1" ]; then
            aws s3api create-bucket --bucket $S3_BUCKET
          else
            aws s3api create-bucket --bucket $S3_BUCKET --region $AWS_REGION --create-bucket-configuration LocationConstraint=$AWS_REGION
          fi
          echo "Making bucket public"
          aws s3api put-bucket-policy --bucket $S3_BUCKET --policy '{
            "Version": "2012-10-17",
            "Statement": [{
              "Sid": "PublicReadGetObject",
              "Effect": "Allow",
              "Principal": "*",
              "Action": "s3:GetObject",
              "Resource": "arn:aws:s3:::'"$S3_BUCKET"'/*"
            }]
          }'
          echo "Setting website configuration"
          aws s3 website s3://$S3_BUCKET --index-document index.html
        fi
        aws s3 sync ./ s3://$S3_BUCKET --region $AWS_REGION --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}

